name: gap_cure_dashboard
description: Flutter Project by ITCoderz. SDK Version for the app is 3.10.6 .

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  dropdown_button2: ^2.3.6
  google_maps_flutter_web: ^0.5.2
  google_maps_flutter: ^2.3.1
  data_table_2: ^2.5.5
  get: ^4.6.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.2


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/poppins/
    - assets/fonts/neutrif_pro/
    - assets/images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: NeutrifPro
      fonts:
        - asset: assets/fonts/neutrif_pro/NeutrifPro-Bold.ttf
        - asset: assets/fonts/neutrif_pro/NeutrifPro-Light.ttf
        - asset: assets/fonts/neutrif_pro/NeutrifPro-Medium.ttf
        - asset: assets/fonts/neutrif_pro/NeutrifPro-Regular.ttf
